name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: dj.profile.svg
          token: ${{ secrets.metrics }}
          base: header, activity
          plugin_introduction: yes
          plugin_topics: yes
          plugin_languages: yes
          plugin_topics_limit: 8
          plugin_topics_mode: labels
          plugin_topics_sort: starred
          plugin_calendar: yes
          plugin_calendar_limit: 2
